name: Deploy and Take Screenshot

on:
  push:
    branches:
      - main

jobs:
  take-screenshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Puppeteer screenshot
        run: |
          npx ts-node scripts/screenshot.ts
        env:
          URL: https://your-deployed-url.vercel.app
